version: '3'

services:
  app:
    image: golang:1.17
    container_name: go
    volumes:
      - "./api:/go/api/"
    ports:
      - "80:8080"
    working_dir: /go/api/${PROJECT_NAME}/
    command: go run /go/api/main.go
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    tty: true
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=devbook
      - MYSQL_ROOT_PASSWORD=root